name: Hello World Debug

on:
  workflow_dispatch:

jobs:
  debug_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: |
          echo "Hello world"
          echo "cd: $(pwd)"

      - name: Check files structure
        run: |
          ls -R

      - name: Download Engine Binary
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'adic3x/blog_generator'
          version: 'latest'
          file: 'blog_engine_linux'
          target: 'generator'
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Make executable
        run: chmod +x ./generator

      - name: Run version check
        run: ./generator -V
