name: Hello World Debug

on:
  workflow_dispatch:

jobs:
  debug_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: |
          echo "Hello world"
          echo "cd: $(pwd)"

      - name: Check files structure
        run: |
          ls -R
          
      - name: Download Engine Binary via GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo adic3x/blog_generator \
                              --pattern 'blog_generator_linux' \
                              --output blog_generator \
                              --clobber

      - name: Make executable
        run: chmod +x ./blog_generator

      - name: Run version check
        run: ./blog_generator -V
